// Reader for the generated tool manifest.
//
// tools-manifest.json sits at the package root and is GENERATED by
// scripts/generate-manifest.mjs as part of `npm run build`. It is never hand-edited.
// Its contents come from src/index.ts's REGISTERED_TOOL_NAMES, which every tool
// registration passes through, so the manifest and the runtime registry are the same
// data by construction rather than by anyone remembering to update a literal.
//
// Do not replace this with a count of `server.registerTool(` occurrences in source
// text. That is source scraping: it breaks silently the moment the registration API
// is renamed, and it reports whatever the grep happens to match rather than what the
// server actually registered.

import { readFileSync } from "node:fs";

export interface ToolManifest {
  generated_by: string;
  count: number;
  tools: string[];
}

/** Resolves from build/*.js to the package root, in the repo and when installed. */
const MANIFEST_URL = new URL("../tools-manifest.json", import.meta.url);

export function readToolManifest(): ToolManifest | null {
  try {
    return JSON.parse(readFileSync(MANIFEST_URL, "utf8")) as ToolManifest;
  } catch {
    // Absent only before the first build has generated it. Callers pass a live
    // fallback so a fresh checkout never prints a wrong number.
    return null;
  }
}

/**
 * The generated tool count.
 *
 * `fallback` should be the caller's live registry length where one is available, so
 * the pre-first-build case degrades to the true runtime number rather than a stale
 * literal. tests/v2-boundary-tools.test.mjs asserts the two are equal.
 */
export function toolCount(fallback?: number): number {
  const m = readToolManifest();
  if (m && typeof m.count === "number") return m.count;
  return fallback ?? 0;
}
